### PR TITLE
add austinp

### PR DESCRIPTION
**Pull request by matthiasdiener**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by matthiasdiener** [comment]
This is ready for review.

**Comment by synapticarbors** [comment]
@matthiasdiener -- Thanks for the PR. This is touching a lot of files that I typically don't see hand-edited. Could you give me a brief overview explaining the rationale for the changes?

**Comment by matthiasdiener** [comment]
> @matthiasdiener -- Thanks for the PR. This is touching a lot of files that I typically don't see hand-edited. Could you give me a brief overview explaining the rationale for the changes?

The only hand edited files are the meta.yaml and build.sh (and the added patch to support newer compilers). The other changes are just due to rerendering. The handmade changes were necessary to support building austinp on Linux.

**Comment by synapticarbors** [comment]
So you did the re-render locally, and then made other commits on top of the rerender? I thought it was all hand edited, since I didn't see the isolated re-render commit with the auto-generated commit message.

**Comment by matthiasdiener** [comment]
> So you did the re-render locally, and then made other commits on top of the rerender?

Yes, that is what I did.

**Comment by matthiasdiener** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
